<h1 style='text-aling:center;color:Navy'>  Big Data Systems - Fall 2021  </h1>
<h1 style='text-aling:center;color:Navy'>  Assignment 2  </h1>

This assignment is focused on Big Data Storage Systems. In particular we will work with the following: 
- MongoDB 
- Redis

To complete the assignment, you should complete this notebook by filling in the cells provided.

Submission Deadline: This assignment is due Monday, Oct 11 at 11:59 P.M.

A few notes before you start:
- Directly sharing answers is not okay, but discussing problems with other students is encouraged.
- You should start early so that you have time to get help if you're stuck.

- Before continuing the assignment, select "Save and Checkpoint" in the File menu and then execute the submit cell below. The result will contain a link that you can use to check that your assignment has been submitted successfully. If you submit more than once before the deadline, we will only grade your final submission. If you mistakenly submit the wrong one, you can head to okpy.org and flag the correct version. There will be another submit cell at the end of the assignment when you finish!

<hr style="border-top: 5px solid orange; margin-top: 1px; margin-bottom: 1px"></hr>
<br>
Before you begin completing the assignment, execute the following cell to load the provided tests.

In [ ]:
# Don't change this cell; just run it. 
# When you log-in please hit return (not shift + return) after typing in your email
from client.api.notebook import Notebook
ok = Notebook('Assignment2.ok')

In [ ]:
_ = ok.submit()

<hr style="border-top: 5px solid orange; margin-top: 1px; margin-bottom: 1px"></hr>

<hr style="border-top: 5px solid purple; margin-top: 1px; margin-bottom: 1px"></hr>

# <span style="font-size:35px;color:#3665af">Section 1: MongoDB </span>

<hr>
In this section, we will practice how to use MongoDB. <br>

## Pre-reqs:

You need to have your environment set up on Google Cloud working. Please refer to the provided Google Cloud instructions for this setup. <br>

<div style="font-size:30px;color:#3665af;background-color:#E9E9F5;padding:10px;">1. Environment Setup </div>

<br>

<div style="font-size:20px;color:#F1F8FC;background-color:#0095EA;padding:10px;">1.1. Uploading your files to the cloud </div>

We need to upload the file cities.txt to the bucket. In the following procedure we will refer to the bucket name as **bigdatasystem\_1234\_bucket** so you need to replace that with your bucket name.

<div style="font-size:20px;color:#F1F8FC;background-color:#0095EA;padding:10px;">1.2. Creating and uploading a Bucket </div>

1. Go to the cloud console.
2. Using the menu select Storage and then select your bucket. If you don't have one, you need to create one.
3. Drag your file to the bucket. 


![Console](img/Storage.PNG)

<div style="font-size:20px;color:#F1F8FC;background-color:#0095EA;padding:10px;">1.3. Configuring a MongoDB Instance</div>

Google cloud provides two ways to deploy a MongoDB instance. The first way is by creating a MongoDB Cluster. For this lab that option is too costly. The second one is by deploying a container. We will implement this latter approach. 

To do that, first open the Google Cloud console. Go to the web console and select your project, then click on the console icon on the top right corner.

![Console launcher](img/console.png)

__ After you open your console, you should have something like this: __
<hr>

![Console](img/console2.png)

<br>

<div style="font-size:20px;color:#F1F8FC;background-color:#0095EA;padding:10px;">1.4. Pulling Docker image</div>

To pull the docker image just type and run:
<pre style="background-color: #ebece4;padding: 10px;border-left: solid 4px orange;">
gcloud docker -- pull launcher.gcr.io/google/mongodb3:latest
</pre>


<div style="font-size:20px;color:#F1F8FC;background-color:#0095EA;padding:10px;">1.5. Creating the necessary directories</div>

Just run:
<pre style="background-color: #ebece4;padding: 10px;border-left: solid 4px orange;">
mkdir -p ~/mongo/data/shard1
mkdir -p ~/mongo/files
</pre>

We need to pull the _cities.txt_ file from the bucket to the console.
<pre style="background-color: #ebece4;padding: 10px;border-left: solid 4px orange;">
gsutil cp gs://bigdatasystem_1234_bucket/cities.txt ~/mongo/files/cities.txt
</pre>
    
<div class="alert alert-block alert-info">
<b>NOTE:</b> Remember to use your bucket name
</div>

<div style="font-size:20px;color:#F1F8FC;background-color:#0095EA;padding:10px;">1.6. Running docker</div>

To create a MongoDB instance just run this command. 

<pre style="background-color: #ebece4;padding: 10px;border-left: solid 4px orange;">
docker run \
  --name server1 \
  -p 27017:27017 \
  -v ~/mongo/data/shard1:/data/db \
  -v ~/mongo/files:/files \
  -d \
  launcher.gcr.io/google/mongodb3
</pre>

- --name sets the name of the docker container 
- -p sets the port for MongoDB, in this case 27017
- -v maps a host directory to the container; e.g. maps the ~/mongo/data/shard1 to the /data/db in the container
- -d indicates the process to run in the container 


**Once you run this command, you should get an hexadecimal id of the image**.<br><br>

<div style="font-size:20px;color:#F1F8FC;background-color:#0095EA;padding:10px;">1.7. Docker Reference:</div>

[Reference](https://docs.docker.com/) and [Cheat Sheet](https://github.com/wsargent/docker-cheat-sheet)

#### To check which are the dockers containers currently executing 
Run:
<pre style="background-color: #ebece4;padding: 10px;border-left: solid 4px orange;">
docker ps
</pre>

#### To stop a docker container
Run:
<pre style="background-color: #ebece4;padding: 10px;border-left: solid 4px orange;">
docker stop \<dockerName\>
</pre>
Example:
<pre style="background-color: #ebece4;padding: 10px;border-left: solid 4px orange;">
docker stop server1
</pre>

#### To remove (destroy) a docker container
Run:
<pre style="background-color: #ebece4;padding: 10px;border-left: solid 4px orange;">
docker rm \<dockerName\>
</pre>
Example:
<pre style="background-color: #ebece4;padding: 10px;border-left: solid 4px orange;">
docker rm server1
</pre>

<div style="font-size:30px;color:#3665af;background-color:#E9E9F5;padding:10px;">2. Connecting to MongoDB </div>


To execute the client run:
<pre style="background-color: #ebece4;padding: 10px;border-left: solid 4px orange;">
docker exec -it server1 mongo admin
</pre>

You should get the following output:

![mongo client](img/mongoClient.png)

To end the client just run:
<pre style="background-color: #ebece4;padding: 10px;border-left: solid 4px navy;">
quit();
</pre>

- Create the database **mydb** and the collection **cities**:

<pre style="background-color: #ebece4;padding: 10px;border-left: solid 4px navy;">
#Create the DB if not exists 
use mydb  
#Creates the collection.
db.createCollection("cities")
</pre>

- Verify the existence of the database (mydb) and the database collection (cities):

<pre style="background-color: #ebece4;padding: 10px;border-left: solid 4px navy;">
show dbs
show collections
</pre>

<span style="color:RED">Paste the output of the previous four commands here. </span>

> show dbs
admin   0.000GB
config  0.000GB
local   0.000GB
mydb    0.002GB


> show collections
cities

<div style="font-size:20px;color:#F1F8FC;background-color:#0095EA;padding:10px;">2.1. Load some data</div>


Quit the client so we can use the mongoimport to load data.

<pre style="background-color: #ebece4;padding: 10px;border-left: solid 4px navy;">
quit();
</pre>

- First let's check that we have the file in the correct directory. 

<pre style="background-color: #ebece4;padding: 10px;border-left: solid 4px orange;">
ls -al ~/mongo/files
</pre>
Should list the cities.txt

- We will use the **mongoimport** tool to load documents from a text file. The syntax is:
<pre style="background-color:#dddddd;padding:5px;">
mongoimport  --db <database> --collection <collection> --file <filepath/filename>
</pre>

- So, to execute it through docker just run:
<pre style="background-color: #ebece4;padding: 10px;border-left: solid 4px orange;">
docker exec -it server1 mongoimport  --db mydb --collection cities --file /files/cities.txt
</pre>

<span style="color:RED">Paste the output here. </span>

2021-10-12T01:03:08.654+0000    connected to: localhost
2021-10-12T01:03:09.105+0000    imported 29353 documents


### Question 1:
In English describe the content of the database collection. Also, test the following command:

<pre style="background-color: #ebece4;padding: 10px;border-left: solid 4px navy;">
db.cities.find().pretty()
</pre> 

<span style="color:RED">Include a sample of the result and your description of what that command does below.</span>

{
        "_id" : "01007",
        "city" : "BELCHERTOWN",
        "loc" : [
                -72.410953,
                42.275103
        ],
        "pop" : 10579,
        "state" : "MA"
}
{
        "_id" : "01008",
        "city" : "BLANDFORD",
        "loc" : [
                -72.936114,
                42.182949
        ],
        "pop" : 1240,
        "state" : "MA"
}
{
        "_id" : "01010",
        "city" : "BRIMFIELD",
        "loc" : [
                -72.188455,
                42.116543
        ],
        "pop" : 3706,
        "state" : "MA"
}
{
        "_id" : "01011",
        "city" : "CHESTER",
        "loc" : [
                -72.988761,
                42.279421
        ],
        "pop" : 1688,
        "state" : "MA"
}
{
        "_id" : "01012",
        "city" : "CHESTERFIELD",
        "loc" : [
                -72.833309,
                42.38167
        ],
        "pop" : 177,
        "state" : "MA"
}
{
        "_id" : "01013",
        "city" : "CHICOPEE",
        "loc" : [
                -72.607962,
                42.162046
        ],
        "pop" : 23396,
        "state" : "MA"
}
{
        "_id" : "01020",
        "city" : "CHICOPEE",
        "loc" : [
                -72.576142,
                42.176443
        ],
        "pop" : 31495,
        "state" : "MA"
}
{
        "_id" : "01022",
        "city" : "WESTOVER AFB",
        "loc" : [
                -72.558657,
                42.196672
        ],
        "pop" : 1764,
        "state" : "MA"
}
{
        "_id" : "01026",
        "city" : "CUMMINGTON",
        "loc" : [
                -72.905767,
                42.435296
        ],
        "pop" : 1484,
        "state" : "MA"
}
{
        "_id" : "01027",
        "city" : "MOUNT TOM",
        "loc" : [
                -72.679921,
                42.264319
        ],
        "pop" : 16864,
        "state" : "MA"
}
{
        "_id" : "01028",
        "city" : "EAST LONGMEADOW",
        "loc" : [
                -72.505565,
                42.067203
        ],
        "pop" : 13367,
        "state" : "MA"
}
{
        "_id" : "01030",
        "city" : "FEEDING HILLS",
        "loc" : [
                -72.675077,
                42.07182
        ],
        "pop" : 11985,
        "state" : "MA"
}
{
        "_id" : "01031",
        "city" : "GILBERTVILLE",
        "loc" : [
                -72.198585,
                42.332194
        ],
        "pop" : 2385,
        "state" : "MA"
}
{
        "_id" : "01032",
        "city" : "GOSHEN",
        "loc" : [
                -72.844092,
                42.466234
        ],
        "pop" : 122,
        "state" : "MA"
}
{
        "_id" : "01033",
        "city" : "GRANBY",
        "loc" : [
                -72.520001,
                42.255704
        ],
        "pop" : 5526,
        "state" : "MA"
}
{
        "_id" : "01034",
        "city" : "TOLLAND",
        "loc" : [
                -72.908793,
                42.070234
        ],
        "pop" : 1652,
        "state" : "MA"
}
{
        "_id" : "01035",
        "city" : "HADLEY",
        "loc" : [
                -72.571499,
                42.36062
        ],
        "pop" : 4231,
        "state" : "MA"
}
{
        "_id" : "01036",
        "city" : "HAMPDEN",
        "loc" : [
                -72.431823,
                42.064756
        ],
        "pop" : 4709,
        "state" : "MA"
}
{
        "_id" : "01001",
        "city" : "AGAWAM",
        "loc" : [
                -72.622739,
                42.070206
        ],
        "pop" : 15338,
        "state" : "MA"
}
{
        "_id" : "01002",
        "city" : "CUSHMAN",
        "loc" : [
                -72.51565,
                42.377017
        ],
        "pop" : 36963,
        "state" : "MA"
}
Type "it" for more
>

In the db.cities.find().pretty() command, the find() method helps in fetching the data from the database where as the pretty method displays the results in an easy to readable format.

<hr style="border-top: 1px solid red; margin-top: 20px; margin-bottom: 1px"></hr>

##### Using what you learned in class and [MongoDB Reference]( https://docs.mongodb.com/manual/reference/mongo-shell/ ) answer the following queries using the cities collection.

<hr style="border-top: 1px solid red; margin-top: 20px; margin-bottom: 1px"></hr>


### Question 2:
List all the cities of the State of Colorado.

<span style="color:RED">Place your code and a sample of the result here.</span>

In [33]:
db.cities.distinct( "city", {state:"CO" });


Sample Result : [
        "ARVADA",
        "AURORA",
        "BROOMFIELD",
        "WESTMINSTER",
        "COMMERCE CITY",
        "LAFAYETTE",
        "LOUISVILLE",
        "WHEAT RIDGE",
        "BENNETT",
        "AGATE",
        "BYERS",
        "CASTLE ROCK",
        "DEER TRAIL",
        "CHERRY HILLS VIL",
        "ENGLEWOOD",
        "FRANKTOWN",
        "KIOWA",
        "LARKSPUR",
        "ELIZABETH",
        "LITTLETON",
        "GREENWOOD VILLAG",
        "ELBERT",
        "HIGHLANDS RANCH",
        "MONUMENT",
        "PALMER LAKE",
        "PARKER",
        "DECKERS",
        "STRASBURG",
        "WATKINS",
        "DENVER",
        "MOUNTAIN VIEW",
        "LAKEWOOD",
        "EDGEWATER",
        "BOW MAR",
        "FEDERAL HEIGHTS",
        "THORNTON",
        "GLENDALE",
        "NORTHGLENN",
        "BOULDER",
        "GOLDEN",
        "BLACK HAWK",
        "BOND",
        "COALMONT",
        "CLIMAX",
        "CLARK",
        "CONIFER",
        "BAILEY",
        "KEYSTONE",
        "GRANBY",
        "EVERGREEN",
        "GRAND LAKE",
        "FAIRPLAY",
        "FOXTON",
        "IDAHO SPRINGS",
        "JAMESTOWN",
        "KREMMLING",
        "JEFFERSON",
        "NEDERLAND",
        "OAK CREEK",
        "MC COY",
        "PARSHALL",
        "PINE",
        "PINECLIFFE",
        "ROLLINSVILLE",
        "MORRISON",
        "LEADVILLE",
        "WARD",
        "STEAMBOAT SPRING",
        "WALDEN",
        "LONGMONT",
        "TOPONAS",
        "ALLENSPARK",
        "DRAKE",
        "DACONO",
        "BERTHOUD",
        "ERIE",
        "ESTES PARK",
        "FORT COLLINS",
        "BELLVUE",
        "VIRGINIA DALE",
        "JOHNSTOWN",
        "LAPORTE",
        "LOVELAND",
        "LYONS",
        "MILLIKEN",
        "RED FEATHER LAKE",
        "WELLINGTON",
        "BRIGGSDALE",
        "CARR",
        "LOCHBUI",
        "AULT",
        "EATON",
        "EVANS",
        "WATTENBURG",
        "GALETON",
        "WINDSOR",
        "GILL",
        "GARDEN CITY",
        "GREELEY",
        "KERSEY",
        "LA SALLE",
        "NUNN",
        "ORCHARD",
        "PIERCE",
        "PLATTEVILLE",
        "ROGGEN",
        "WELDONA",
        "HUDSON",
        "HOYT",
        "FORT MORGAN",
        "AKRON",
        "AMHERST",
        "ATWOOD",
        "BRUSH",
        "CROOK",
        "FLEMING",
        "ECKLEY",
        "GROVER",
        "HENDERSON",
        "KEENESBURG",
        "HAXTUN",
        "HILLROSE",
        "HOLYOKE",
        "HALE",
        "ILIFF",
        "NEW RAYMER",
        "OTIS",
        "OVID",
        "PADRONI",
        "PEETZ",
        "SEDGWICK",
        "SNYDER",
        "STERLING",
        "STONEHAM",
        "VERNON",
        "LAST CHANCE",
        "LAIRD",
        "YUMA",
        "ANTON",
        "ARAPAHOE",
        "ARRIBA",
        "BETHUNE",
        "BURLINGTON",
        "JULESBURG",
        "LINDON",
        "WILLARD",
        "CALHAN",
        "NORTH POLE",
        "CHEYENNE WELLS",
        "COPE",
        "DIVIDE",
        "GENOA",
        "GUFFEY",
        "HUGO",
        "JOES",
        "KARVAL",
        "KIRK",
        "KIT CARSON",
        "LAKE GEORGE",
        "LIMON",
        "MANITOU SPRINGS",
        "MATHESON",
        "PEYTON",
        "RAMAH",
        "RUSH",
        "SEIBERT",
        "SIMLA",
        "STRATTON",
        "UNITED STATES AI",
        "FLAGLER",
        "FLORISSANT",
        "FOUNTAIN",
        "VONA",
        "WOODLAND PARK",
        "YODER",
        "COLORADO SPRINGS",
        "FORT CARSON",
        "CHEYENNE MTN AFB",
        "PUEBLO",
        "AGUILAR",
        "PUEBLO WEST",
        "ARLINGTON",
        "BOONE",
        "BEULAH",
        "NORTH AVONDALE",
        "BRANDON",
        "BRANSON",
        "BRISTOL",
        "CHIVINGTON",
        "CAMPO",
        "HARTMAN",
        "CADDOA",
        "HASWELL",
        "FARISITA",
        "HOLLY",
        "VILLEGREEN",
        "TIMPAS",
        "LAMAR",
        "DEORA",
        "FOWLER",
        "GRANADA",
        "CUCHARA",
        "OLNEY SPRINGS",
        "DELHI",
        "UTLEYVILLE",
        "ORDWAY",
        "ROCKY FORD",
        "RYE",
        "TOWNER",
        "MC CLAVE",
        "SPRINGFIELD",
        "TRINCHERA",
        "LYCAN",
        "SUGAR CITY",
        "JANSEN",
        "VILAS",
        "FARISTA",
        "MANZANOLA",
        "WALSH",
        "WESTON",
        "ARBOLES",
        "BAYFIELD",
        "BLANCA",
        "CENTER",
        "ANTONITO",
        "CREEDE",
        "FORT GARLAND",
        "WILEY",
        "LA GARITA",
        "HOOPER",
        "IGNACIO",
        "LA JARA",
        "MONTE VISTA",
        "MOSCA",
        "MOFFAT",
        "ALAMOSA",
        "SAN ACACIO",
        "SANFORD",
        "PAGOSA SPRINGS",
        "SAGUACHE",
        "SAN PABLO",
        "SOUTH FORK",
        "MESITA",
        "VILLA GROVE",
        "SALIDA",
        "ALMONT",
        "CIMARRON",
        "CRESTED BUTTE",
        "FLORENCE",
        "CANON CITY",
        "GRANITE",
        "GUNNISON",
        "HOWARD",
        "BUENA VISTA",
        "LAKE CITY",
        "PENROSE",
        "PARLIN",
        "PITKIN",
        "POWDERHORN",
        "TWIN LAKES",
        "WETMORE",
        "WESTCLIFFE",
        "NATHROP",
        "DURANGO",
        "DOLORES",
        "CORTEZ",
        "DOVE CREEK",
        "EGNAR",
        "HESPERUS",
        "LEWIS",
        "MANCOS",
        "CAHONE",
        "PLEASANT VIEW",
        "TOWAOC",
        "YELLOW JACKET",
        "AUSTIN",
        "BEDROCK",
        "MONTROSE",
        "CEDAREDGE",
        "HOTCHKISS",
        "NATURITA",
        "NORWOOD",
        "CRAWFORD",
        "DELTA",
        "OLATHE",
        "OPHIR",
        "ECKERT",
        "NUCLA",
        "REDVALE",
        "RIDGWAY",
        "SILVERTON",
        "SOMERSET",
        "PAONIA",
        "TELLURIDE",
        "PLACERVILLE",
        "GRAND JUNCTION",
        "FRUITVALE",
        "OURAY",
        "LOMA",
        "MACK",
        "PALISADE",
        "WHITEWATER",
        "FRUITA",
        "GLENWOOD SPRINGS",
        "DINOSAUR",
        "CLIFTON",
        "GATEWAY",
        "ASPEN",
        "BASALT",
        "CRAIG",
        "DE BEQUE",
        "EAGLE",
        "COLLBRAN",
        "ELK SPRINGS",
        "BATTLEMENT MESA",
        "HAMILTON",
        "GYPSUM",
        "MARBLE",
        "HAYDEN",
        "MAYBELL",
        "NEW CASTLE",
        "MESA",
        "RANGELY",
        "RIFLE",
        "SILT",
        "SNOWMASS",
        "MEEKER",
        "SLATER",
        "MEREDITH",
        "VAIL"
]

SyntaxError: invalid syntax (<ipython-input-33-4cb136a5fa51>, line 4)


### Question 3:
List the first 10 cities of the State of Colorado.

<span style="color:RED">Place your code and a sample of the result here.

    

{ "_id" : "AKRON" }
{ "_id" : "AMHERST" }
{ "_id" : "ANTON" }
{ "_id" : "ASPEN" }
{ "_id" : "ALLENSPARK" }
{ "_id" : "ATWOOD" }
{ "_id" : "AULT" }
{ "_id" : "AURORA" }
{ "_id" : "AUSTIN" }
{ "_id" : "BATTLEMENT MESA" }


</span>

In [ ]:
db.cities.aggregate( [ { sort : { 'city' : -1}},
    { match : { 'state' : 'CO'}}, { group : {'_id' :  ' city'}}, {$limit : 10}]);

### Question 4:
List the 10 cities of the State of Colorado with largest populations.

<span style="color:RED">Place your code and a sample of the result here.</span>

In [ ]:
db.cities.aggregate(
[

{$match : { 'state' : 'CO'}},
    {$group : {_id :  '$city',
              total_population : {$sum : '$pop'}
              }},
    {$sort : { total_population : -1}},
    {$limit : 10}

 ]
 );


Sample Result :
    
{ "_id" : "DENVER", "total_population" : 451182 }
{ "_id" : "COLORADO SPRINGS", "total_population" : 340404 }
{ "_id" : "AURORA", "total_population" : 237454 }
{ "_id" : "PUEBLO", "total_population" : 112549 }
{ "_id" : "FORT COLLINS", "total_population" : 111706 }
{ "_id" : "BOULDER", "total_population" : 108968 }
{ "_id" : "LAKEWOOD", "total_population" : 101326 }
{ "_id" : "ARVADA", "total_population" : 100918 }
{ "_id" : "LITTLETON", "total_population" : 87954 }
{ "_id" : "LONGMONT", "total_population" : 67696 }

### Question 5:
List the 10 cities with largest populations.

<span style="color:RED">Place your code and a sample of the result here.</span>

In [ ]:
db.cities.aggregate( [

{$group : {_id :  '$city',
              total_population : {$sum : '$pop'}
              }},
    {$sort : { total_population : -1}},
    {$limit : 10}
] );

Sample Result : 
   
{ "_id" : "CHICAGO", "total_population" : 2452177 }
{ "_id" : "BROOKLYN", "total_population" : 2341387 }
{ "_id" : "HOUSTON", "total_population" : 2123053 }
{ "_id" : "LOS ANGELES", "total_population" : 2102295 }
{ "_id" : "PHILADELPHIA", "total_population" : 1639862 }
{ "_id" : "NEW YORK", "total_population" : 1476790 }
{ "_id" : "BRONX", "total_population" : 1209548 }
{ "_id" : "SAN DIEGO", "total_population" : 1054316 }
{ "_id" : "DALLAS", "total_population" : 999042 }
{ "_id" : "DETROIT", "total_population" : 967468 }

<hr style="border: 1px double blue;" >

## Map-Reduce with MongoDB

We can run map-reduce jobs on Mongodb. Let's count the number of cities per state:

<pre style="background-color: #ebece4;padding: 10px;border-left: solid 4px navy;">
db.cities.mapReduce(
                    function()           { emit(this.state,1); }, 
                    function(key,values) {return key,Array.sum(values);}, 
                    { out: "citiesPerState" } 
                   )
</pre>

This code will generate a new collection instead of displaying the result. 
Use the commands discussed before to list the collections and to get the information from the new collection.

### Question 6:
<span style="color:RED">Place your code output (map-reduce) here.</span>

{
        "result" : "citiesPerState",
        "timeMillis" : 200,
        "counts" : {
                "input" : 29353,
                "emit" : 29353,
                "reduce" : 353,
                "output" : 51
        },
        "ok" : 1
}

### Question 7:
<span style="color:RED">Place the list of collections here.</span>

Query - 
show collection

Sample Result -
cities
citiesPerState

### Question 8:
<span style="color:RED">Place the content of the new collection here.</span>

Query - 
db.citiesPerState.find().pretty()

Sample Result - 

{ "_id" : "AK", "value" : 195 }
{ "_id" : "AL", "value" : 567 }
{ "_id" : "AR", "value" : 578 }
{ "_id" : "AZ", "value" : 270 }
{ "_id" : "CA", "value" : 1516 }
{ "_id" : "CO", "value" : 414 }
{ "_id" : "CT", "value" : 263 }
{ "_id" : "DC", "value" : 24 }
{ "_id" : "DE", "value" : 53 }
{ "_id" : "FL", "value" : 804 }
{ "_id" : "GA", "value" : 635 }
{ "_id" : "HI", "value" : 80 }
{ "_id" : "IA", "value" : 922 }
{ "_id" : "ID", "value" : 244 }
{ "_id" : "IL", "value" : 1237 }
{ "_id" : "IN", "value" : 676 }
{ "_id" : "KS", "value" : 715 }
{ "_id" : "KY", "value" : 809 }
{ "_id" : "LA", "value" : 464 }
{ "_id" : "MA", "value" : 474 }
{ "_id" : "MD", "value" : 420 }
{ "_id" : "ME", "value" : 410 }
{ "_id" : "MI", "value" : 876 }
{ "_id" : "MN", "value" : 882 }
{ "_id" : "MO", "value" : 994 }
{ "_id" : "MS", "value" : 363 }
{ "_id" : "MT", "value" : 314 }
{ "_id" : "NC", "value" : 705 }
{ "_id" : "ND", "value" : 391 }
{ "_id" : "NE", "value" : 574 }
{ "_id" : "NH", "value" : 218 }
{ "_id" : "NJ", "value" : 540 }
{ "_id" : "NM", "value" : 276 }
{ "_id" : "NV", "value" : 104 }
{ "_id" : "NY", "value" : 1595 }
{ "_id" : "OH", "value" : 1007 }
{ "_id" : "OK", "value" : 586 }
{ "_id" : "OR", "value" : 384 }
{ "_id" : "PA", "value" : 1458 }
{ "_id" : "RI", "value" : 69 }
{ "_id" : "SC", "value" : 350 }
{ "_id" : "SD", "value" : 384 }
{ "_id" : "TN", "value" : 582 }
{ "_id" : "TX", "value" : 1671 }
{ "_id" : "UT", "value" : 205 }
{ "_id" : "VA", "value" : 816 }
{ "_id" : "VT", "value" : 243 }
{ "_id" : "WA", "value" : 484 }
{ "_id" : "WI", "value" : 716 }
{ "_id" : "WV", "value" : 656 }
{ "_id" : "WY", "value" : 140 }

### Map-Reduce - Question 9:
Generate a collection called **populationPerState** that contains the population of each state.

<span style="color:RED">Place your code, code output and a sample of the result here.</span>

Code - 
    
db.cities.mapReduce(
                    function()           { emit(this.state,this.pop); }, 
                    function(key,values) {return key,Array.sum(values);}, 
                    { out: "populationPerState" } 
                   )

Output - 

{
        "result" : "populationPerState",
        "timeMillis" : 231,
        "counts" : {
                "input" : 29353,
                "emit" : 29353,
                "reduce" : 353,
                "output" : 51
        },
        "ok" : 1
}

Query - db.populationPerState.find().pretty()

Sample Result - 

{ "_id" : "AK", "value" : 544698 }
{ "_id" : "AL", "value" : 4040587 }
{ "_id" : "AR", "value" : 2350725 }
{ "_id" : "AZ", "value" : 3665228 }
{ "_id" : "CA", "value" : 29754890 }
{ "_id" : "CO", "value" : 3293755 }
{ "_id" : "CT", "value" : 3287116 }
{ "_id" : "DC", "value" : 606900 }
{ "_id" : "DE", "value" : 666168 }
{ "_id" : "FL", "value" : 12686644 }
{ "_id" : "GA", "value" : 6478216 }
{ "_id" : "HI", "value" : 1108229 }
{ "_id" : "IA", "value" : 2776420 }
{ "_id" : "ID", "value" : 1006749 }
{ "_id" : "IL", "value" : 11427576 }
{ "_id" : "IN", "value" : 5544136 }
{ "_id" : "KS", "value" : 2475285 }
{ "_id" : "KY", "value" : 3675484 }
{ "_id" : "LA", "value" : 4217595 }
{ "_id" : "MA", "value" : 6016425 }

### Map-Reduce - Question 10:
Generate a collection called **totalPopulation** that contains the entire population of the USA.

<span style="color:RED">Place your code, code output and a sample of the result here.</span>
> Hint: you can use your previous computed collection.

Code - 

db.populationPerState.mapReduce(
                    function()           { emit("USA",this.value); }, 
                    function(key,values) {return key,Array.sum(values);}, 
                    { out: "totalPopulation" } 
                   )
        
Sample Result-      
 {
        "result" : "totalPopulation",
        "timeMillis" : 49,
        "counts" : {
                "input" : 51,
                "emit" : 51,
                "reduce" : 1,
                "output" : 1
        },
        "ok" : 1
}


Result- db.totalPopulation.find().pretty() - 

{ "_id" : "USA", "value" : 248408400 }

<span style="text-align:center;font-size:30px;color:#2F632A">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;STOP AND DELETE YOUR DOCKER WHEN YOU ARE FINISHED 
</span>
<br>

<hr style="border-top: 5px solid purple; margin-top: 1px; margin-bottom: 1px"></hr>

# <span style="font-size:35px;color:#3665af">Section 2: REDIS </span>
<hr>

The objective of this part of the assignment is to introduce the use of REDIS (an in-memory data store) to collect data from various sources for subsequent data processing. 

For this assignment, we will be using REDIS on Google Cloud and Twitter Python libraries.

<b><u>Notebook Layout (Table of contents):</u></b>
1. Environment Set-up
   - Deployment a REDIS Cluster
   - Network Configuration
   - Enabling Remote Access
   - Installing Python libraries
2. Getting Familiar with REDIS
3. Retrieving Information From Twitter
   - Creating Twitter Credentials
   - Accessing Twitter
   - Saving Tweets to REDIS
   - Retrieving Tweets from REDIS
4. Load Database From CSV

<div style="font-size:30px;color:#3665af;background-color:#E9E9F5;padding:10px;">1. Environment Setup </div>

For this assignment we will be using the REDIS deployment on Google Cloud. Please follow the instructions to set up the cluster. You can opt to install REDIS on your own system. We don't recommend this approach though.<br><br>

<div style="font-size:20px;color:#F1F8FC;background-color:#0095EA;padding:10px;">1.1. Deployment of a REDIS Cluster </div>

Go to the Menu and select **Cloud Launcher**. Then use the search box, and search REDIS.

<img src="img/redis_launcher.png" style="width:1000px;">

We will deploy a REDIS cluster using three small-cpu nodes:
- **Name**: redis-1
- **Zone**: us-central1-f
- **Instance Count**: 3
- **Machine Type**: small (1.7Gb memory)
- **Boot Disk size**: 50GB

All other parameters are set to default values. The cost of this deployment is the same as that of any other Virtual Machine (VM) created on the cloud. Your deployment configuration should be similar to this:<br>

<img src="img/redis_deployment.png" style="width:1000px;">

<div style="font-size:20px;color:#F1F8FC;background-color:#0095EA;padding:10px;">1.2. Network Configuration </div>

Once you have your cluster deployed, we need to setup a firewall rule to allow us access from our Jupyter-Notebook. To do that, go to the menu, and select **VPC Network**. Then select Firewall Rules and create a new rule as depicted below:


![Terminal](img/network.png)

<div style="font-size:20px;color:#F1F8FC;background-color:#0095EA;padding:10px;">
    1.3. Enabling Remote Access to REDIS
</div>

After creating the firewall rule, we also need to configure REDIS to allow access from the external network. Follow this procedure to accomplish that:

- Open the SSH terminal to the main server, by selecting SSH on the _redis-1-db-vm-0_ VM (the Compute Engine menu on the Cloud).

<img src="img/redis_vm.png" style="width:550px;">
 
- Launch the REDIS Client on the console 

<pre style="background-color: #ebece4;padding: 10px;border-left: solid 4px orange;">
redis-cli
</pre>

- Within the client change the config to disable protected mode

<pre style="background-color: #ebece4;padding: 10px;border-left: solid 4px navy;">
CONFIG SET protected-mode no
</pre>
You should get an **OK** message. Then type:
<pre style="background-color: #ebece4;padding: 10px;border-left: solid 4px navy;">
quit
</pre>

Once this is completed, we should be able to access REDIS through the public ip we get on the VM list

<img src="img/redis_vm_ip.png" style="width:550px;">

<div style="font-size:20px;color:#F1F8FC;background-color:#0095EA;padding:10px;">
    1.4. Installing Python Libraries
</div>

You need to install two libraries for this assignment: 
- REDIS library, and
- Twitter library.

- Within your notebook environment, open a new terminal (New -> Terminal), and run

<pre style="background-color: #ebece4;padding: 10px;border-left: solid 4px orange;">
pip install tweepy
pip install redis
</pre>

<div style="font-size:30px;color:#3665af;background-color:#E9E9F5;padding:10px;">
    2. Getting Familiar with <b>REDIS</b> 
</div>

You can read about the REDIS commands [here](https://redis.io/commands).

In [26]:
##Import the library
import redis

In [27]:
## Connect to the server
REDIS_SERVER = '34.130.83.48'
REDIS_PORT   = 6379
myRedis = redis.StrictRedis(host=REDIS_SERVER, port=REDIS_PORT, db=0)

In [28]:
## Dropping Everything we got on REDIS
display(myRedis.flushdb())
display(myRedis.flushall())

True

True

In [14]:
print("I'm storing a value on the key 'myKey'")
display(myRedis.set('myKey', 'This is the key value'))
print("I'm reading the value of 'myKey' from REDIS")
display(myRedis.get('myKey'))

I'm storing a value on the key 'myKey'

True

I'm reading the value of 'myKey' from REDIS

b'This is the key value'

In [15]:
print("I'm storing a List on REDIS")

print("Adding elements to the end of the list")
display(myRedis.rpush('weekdays','Tuesday'))
display(myRedis.rpush('weekdays','Wednesday'))
display(myRedis.rpush('weekdays','Thursday'))
display(myRedis.rpush('weekdays','Friday'))
print("Current List Length:", myRedis.llen('weekdays'))
display("Current Weekdays Content:",myRedis.lrange('weekdays',0,-1))


print("Adding elements to the beginning of the list")
display(myRedis.lpush('weekdays','Monday'))

print("Current List Length:", myRedis.llen('weekdays'))
display("Current Weekdays Content:",myRedis.lrange('weekdays',0,-1))

I'm storing a List on REDIS
Adding elements to the end of the list

1

2

3

4

Current List Length: 4

'Current Weekdays Content:'

[b'Tuesday', b'Wednesday', b'Thursday', b'Friday']

Adding elements to the beginning of the list

5

Current List Length: 5

'Current Weekdays Content:'

[b'Monday', b'Tuesday', b'Wednesday', b'Thursday', b'Friday']

In [16]:
print("I'm storing a HASH on REDIS")
print("- Remember that hashes can be used to store documents!")

#create a dictionary
user = {"Name"    :"myName", 
        "Company" :"myCompany", 
        "Address" :"myAddress", 
        "Location":"MyLocation"}

print ("Store to REDIS")
display(myRedis.hmset("userDictionary", user))

print ("Retrieve from REDIS")
display(myRedis.hgetall("userDictionary"))

I'm storing a HASH on REDIS
- Remember that hashes can be used to store documents!
Store to REDIS

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:11: DeprecationWarning: Redis.hmset() is deprecated. Use Redis.hset() instead.
  # This is added back by InteractiveShellApp.init_path()

True

Retrieve from REDIS

{b'Name': b'myName',
 b'Company': b'myCompany',
 b'Address': b'myAddress',
 b'Location': b'MyLocation'}

<div style="font-size:30px;color:#3665af;background-color:#E9E9F5;padding:10px;">
    3. Retrieving Information From Twitter</div>
<br>
<div style="font-size:20px;color:#F1F8FC;background-color:#0095EA;padding:10px;">
    3.1. Creating Twitter Credentials
</div>

In order to be able to access tweets from our application, we need a Tweeter account, consumer keys and access tokens.

To generates these, go to https://apps.twitter.com
and **Create a New App**. Fill in the form and agree with the terms.

Once that's done, select your app and the tab **Keys and Access Tokens**

<img src="img/twitter.PNG" style="width:550px;">

<div style="font-size:20px;color:#F1F8FC;background-color:#0095EA;padding:10px;">
    3.2. Accessing Twitter
</div>

In [20]:
import tweepy
from tweepy import OAuthHandler

consumer_key    = 'L518Ulzo8eESVGhQWoRJtn1fp'
consumer_secret = 'JRIod2wrthFdxjpqaS2hqdXLkamChkfj0L7qSF6kRkfmH0ITWr'
access_token    = '1447706015881854979-63T1EOPqb8e8RtiWkTw2vaMNreliED'
access_secret   = 'H4iLFpUGnAhvnUBzCkyGTirCN7TghgX5j5KWFsbqjOKaS'


auth = OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_secret)
 
api = tweepy.API(auth)

In [21]:
for tweet in tweepy.Cursor(api.home_timeline).items(2):
    # Process a single tweet

    print(tweet._json.keys())
    print()
    print(tweet._json["id"])
    print(tweet._json["text"])
    print(tweet._json["source"])
    print(tweet._json["lang"])
    print(tweet._json["retweeted"])    
    print(tweet._json["retweet_count"])
    print(tweet._json["favorite_count"])
    print()

dict_keys(['created_at', 'id', 'id_str', 'text', 'truncated', 'entities', 'source', 'in_reply_to_status_id', 'in_reply_to_status_id_str', 'in_reply_to_user_id', 'in_reply_to_user_id_str', 'in_reply_to_screen_name', 'user', 'geo', 'coordinates', 'place', 'contributors', 'is_quote_status', 'retweet_count', 'favorite_count', 'favorited', 'retweeted', 'possibly_sensitive', 'possibly_sensitive_appealable', 'lang'])

1447768990303113218
At least 71 loans worth over ₹31,855 crore approved by Yes Bank during the tenure of former chief executive and man… https://t.co/zhty25nTOJ
<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>
en
False
0
9

dict_keys(['created_at', 'id', 'id_str', 'text', 'truncated', 'entities', 'source', 'in_reply_to_status_id', 'in_reply_to_status_id_str', 'in_reply_to_user_id', 'in_reply_to_user_id_str', 'in_reply_to_screen_name', 'user', 'geo', 'coordinates', 'place', 'contributors', 'is_quote_status', 'retweet_count', 'favorite_count', 'favorited', 'retweeted', 'possibly_sensitive', 'possibly_sensitive_appealable', 'lang'])

1447767732192120833
Denmark is among the few countries with a climate law, which has set a target of cutting Denmark’s greenhouse gas e… https://t.co/4fFH1nng63
<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>
en
False
0
13

<div style="font-size:20px;color:#F1F8FC;background-color:#0095EA;padding:10px;">
    3.3. Saving Tweets to REDIS
</div>

In [22]:
# Lets save tweets

howManyTweets = 20

for tweet in tweepy.Cursor(api.home_timeline).items(howManyTweets):
    # Process a single tweet
    
    ##Formatting the tweet 
    redisTweet = {
                  "text"           :tweet._json["text"].encode('utf-8'), 
                  "source"         :tweet._json["source"].encode('utf-8'), 
                  "lang"           :tweet._json["lang"].encode('utf-8'), 
                  "source"         :tweet._json["source"].encode('utf-8'), 
                  "retweet_count"  :tweet._json["retweet_count"], 
                  "favorite_count" :tweet._json["favorite_count"]
                 }

    ## Saving the tweet as HASH
    myRedis.hmset(tweet._json["id"], redisTweet)
    #display(tweet._json["id"])
    
    ## Adding the Tweet id to the list of tweets
    myRedis.rpush("tweets",str(tweet._json["id"]))
       
print("Done!")

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:19: DeprecationWarning: Redis.hmset() is deprecated. Use Redis.hset() instead.

Done!

<div style="font-size:20px;color:#F1F8FC;background-color:#0095EA;padding:10px;">
    3.4. Retrieving Tweets from REDIS
</div>

In [23]:
for id in myRedis.lrange("tweets",0,99):
    print()
    print("Displaying Tweet with ID:",id)
    print("Text:",myRedis.hmget(id,"text"))
    print("ALL DATA:",myRedis.hgetall(id))
    print("========================================================================")

Displaying Tweet with ID: b'1447770248707395591'
Text: [b'Breakdown in talks as China refuses to budge, and Amit Shah takes stock with coal, power ministers amid coal shorta\xe2\x80\xa6 https://t.co/vJygnvrl9M']
ALL DATA: {b'lang': b'en', b'favorite_count': b'0', b'text': b'Breakdown in talks as China refuses to budge, and Amit Shah takes stock with coal, power ministers amid coal shorta\xe2\x80\xa6 https://t.co/vJygnvrl9M', b'source': b'<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>', b'retweet_count': b'0'}
========================================================================

Displaying Tweet with ID: b'1447768990303113218'
Text: [b'At least 71 loans worth over \xe2\x82\xb931,855 crore approved by Yes Bank during the tenure of former chief executive and man\xe2\x80\xa6 https://t.co/zhty25nTOJ']
ALL DATA: {b'lang': b'en', b'favorite_count': b'10', b'text': b'At least 71 loans worth over \xe2\x82\xb931,855 crore approved by Yes Bank during the tenure of former chief executive and man\xe2\x80\xa6 https://t.co/zhty25nTOJ', b'source': b'<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>', b'retweet_count': b'0'}
========================================================================

Displaying Tweet with ID: b'1447767732192120833'
Text: [b'Denmark is among the few countries with a climate law, which has set a target of cutting Denmark\xe2\x80\x99s greenhouse gas e\xe2\x80\xa6 https://t.co/4fFH1nng63']
ALL DATA: {b'lang': b'en', b'favorite_count': b'13', b'text': b'Denmark is among the few countries with a climate law, which has set a target of cutting Denmark\xe2\x80\x99s greenhouse gas e\xe2\x80\xa6 https://t.co/4fFH1nng63', b'source': b'<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>', b'retweet_count': b'0'}
========================================================================

Displaying Tweet with ID: b'1447767274270515200'
Text: [b'Catch the top headlines at 9 AM. #ITLivestream https://t.co/ObEF6dOYgw']
ALL DATA: {b'lang': b'en', b'favorite_count': b'12', b'text': b'Catch the top headlines at 9 AM. #ITLivestream https://t.co/ObEF6dOYgw', b'source': b'<a href="https://studio.twitter.com" rel="nofollow">Twitter Media Studio</a>', b'retweet_count': b'1'}
========================================================================

Displaying Tweet with ID: b'1447766673776283651'
Text: [b'Goooood morning and remember to smile! \xf0\x9f\x98\x81 \n\n#RoyalsFamily https://t.co/oAV1cSMwyB']
ALL DATA: {b'lang': b'en', b'favorite_count': b'376', b'text': b'Goooood morning and remember to smile! \xf0\x9f\x98\x81 \n\n#RoyalsFamily https://t.co/oAV1cSMwyB', b'source': b'<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>', b'retweet_count': b'8'}
========================================================================

Displaying Tweet with ID: b'1447766475268235264'
Text: [b'Start your day with these \xf0\x9d\x97\xa6\xf0\x9d\x97\xba\xf0\x9d\x97\xae\xf0\x9d\x98\x80\xf0\x9d\x97\xb5\xf0\x9d\x97\xb6\xf0\x9d\x97\xbb\xf0\x9d\x97\xb4 hits! \xf0\x9f\x94\xa5\xf0\x9f\x92\x99\n\nPaltan, what is your favourite shot from this compilation? \xf0\x9f\xa4\xa9\xe2\x80\xa6 https://t.co/s4lqMp1iSg']
ALL DATA: {b'lang': b'en', b'favorite_count': b'403', b'text': b'Start your day with these \xf0\x9d\x97\xa6\xf0\x9d\x97\xba\xf0\x9d\x97\xae\xf0\x9d\x98\x80\xf0\x9d\x97\xb5\xf0\x9d\x97\xb6\xf0\x9d\x97\xbb\xf0\x9d\x97\xb4 hits! \xf0\x9f\x94\xa5\xf0\x9f\x92\x99\n\nPaltan, what is your favourite shot from this compilation? \xf0\x9f\xa4\xa9\xe2\x80\xa6 https://t.co/s4lqMp1iSg', b'source': b'<a href="https://studio.twitter.com" rel="nofollow">Twitter Media Studio</a>', b'retweet_count': b'40'}
========================================================================

Displaying Tweet with ID: b'1447766475112996866'
Text: [b"Started as a net bowler \xf0\x9f\x91\x89 now a proud DC Tiger \xf0\x9f\x90\xaf\xf0\x9f\x94\xa5\n\nKulwant Khejroliya's cricketing journey has been nothing short o\xe2\x80\xa6 https://t.co/rkSL7zOmqA"]
ALL DATA: {b'lang': b'en', b'favorite_count': b'90', b'text': b"Started as a net bowler \xf0\x9f\x91\x89 now a proud DC Tiger \xf0\x9f\x90\xaf\xf0\x9f\x94\xa5\n\nKulwant Khejroliya's cricketing journey has been nothing short o\xe2\x80\xa6 https://t.co/rkSL7zOmqA", b'source': b'<a href="https://studio.twitter.com" rel="nofollow">Twitter Media Studio</a>', b'retweet_count': b'3'}
========================================================================

Displaying Tweet with ID: b'1447766474148438020'
Text: [b'Rajasthan government has decided to recall the recently passed \xe2\x80\x98Rajasthan Compulsory Marriage Registration (Amendme\xe2\x80\xa6 https://t.co/exZnI8eEV2']
ALL DATA: {b'lang': b'en', b'favorite_count': b'11', b'text': b'Rajasthan government has decided to recall the recently passed \xe2\x80\x98Rajasthan Compulsory Marriage Registration (Amendme\xe2\x80\xa6 https://t.co/exZnI8eEV2', b'source': b'<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>', b'retweet_count': b'0'}
========================================================================

Displaying Tweet with ID: b'1447766190697291779'
Text: [b'Rajasthan govt rolls back law after uproar over child marriage clause.\n\n#Rajasthan #ChildMarriage \nhttps://t.co/pkQfrJIGJt']
ALL DATA: {b'lang': b'en', b'favorite_count': b'9', b'text': b'Rajasthan govt rolls back law after uproar over child marriage clause.\n\n#Rajasthan #ChildMarriage \nhttps://t.co/pkQfrJIGJt', b'source': b'<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>', b'retweet_count': b'3'}
========================================================================

Displaying Tweet with ID: b'1447765673329893376'
Text: [b'RT @IndiaTodayTech: iOS 15.0.2 brings a patch for a security flaw that Apple says may already be under attack. https://t.co/4Z0RJ2vlZB']
ALL DATA: {b'lang': b'en', b'favorite_count': b'0', b'text': b'RT @IndiaTodayTech: iOS 15.0.2 brings a patch for a security flaw that Apple says may already be under attack. https://t.co/4Z0RJ2vlZB', b'source': b'<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>', b'retweet_count': b'4'}
========================================================================

Displaying Tweet with ID: b'1447765565141962758'
Text: [b'Heavy rainfall leads to waterlogging outside Kempegowda International Airport in Bengaluru.\n#Monsoon LIVE updates\xe2\x80\xa6 https://t.co/ba1gW0plGi']
ALL DATA: {b'lang': b'en', b'favorite_count': b'14', b'text': b'Heavy rainfall leads to waterlogging outside Kempegowda International Airport in Bengaluru.\n#Monsoon LIVE updates\xe2\x80\xa6 https://t.co/ba1gW0plGi', b'source': b'<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>', b'retweet_count': b'1'}
========================================================================

Displaying Tweet with ID: b'1447765358606098433'
Text: [b'Liquidity needed to stem Afghanistan economic, humanitarian crises: UN chief Antonio Guterres\n\n#World \nhttps://t.co/6ahTFdKczZ']
ALL DATA: {b'lang': b'en', b'favorite_count': b'7', b'text': b'Liquidity needed to stem Afghanistan economic, humanitarian crises: UN chief Antonio Guterres\n\n#World \nhttps://t.co/6ahTFdKczZ', b'source': b'<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>', b'retweet_count': b'2'}
========================================================================

Displaying Tweet with ID: b'1447765215685365760'
Text: [b"After the TDP's poor show in the recent local body elections, party president and former CM @ncbn will go on a thre\xe2\x80\xa6 https://t.co/KyUOp7zX9i"]
ALL DATA: {b'lang': b'en', b'favorite_count': b'16', b'text': b"After the TDP's poor show in the recent local body elections, party president and former CM @ncbn will go on a thre\xe2\x80\xa6 https://t.co/KyUOp7zX9i", b'source': b'<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>', b'retweet_count': b'0'}
========================================================================

Displaying Tweet with ID: b'1447765187092627460'
Text: [b'Two people died after a small plane crashed in a densely populated San Diego suburb on Monday.\n\n#World #SanDiego \nhttps://t.co/I9OKeCjYvD']
ALL DATA: {b'lang': b'en', b'favorite_count': b'8', b'text': b'Two people died after a small plane crashed in a densely populated San Diego suburb on Monday.\n\n#World #SanDiego \nhttps://t.co/I9OKeCjYvD', b'source': b'<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>', b'retweet_count': b'2'}
========================================================================

Displaying Tweet with ID: b'1447764916358713345'
Text: [b'A 37-year-old CRPF head constable was allegedly shot by another constable over a tiff in southeast Delhi.\n\n#CRPF\xe2\x80\xa6 https://t.co/brq9XCqv6X']

ALL DATA: {b'lang': b'en', b'favorite_count': b'7', b'text': b'A 37-year-old CRPF head constable was allegedly shot by another constable over a tiff in southeast Delhi.\n\n#CRPF\xe2\x80\xa6 https://t.co/brq9XCqv6X', b'source': b'<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>', b'retweet_count': b'1'}
========================================================================

Displaying Tweet with ID: b'1447764719218020353'
Text: [b'The Ministry of New and Renewable Energy has said that India is set to achieve 450 GW of renewable energy installed\xe2\x80\xa6 https://t.co/FBGn5zz3iu']
ALL DATA: {b'lang': b'en', b'favorite_count': b'9', b'text': b'The Ministry of New and Renewable Energy has said that India is set to achieve 450 GW of renewable energy installed\xe2\x80\xa6 https://t.co/FBGn5zz3iu', b'source': b'<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>', b'retweet_count': b'4'}
========================================================================

Displaying Tweet with ID: b'1447764718685495298'
Text: [b'"7 hard truths you need to know before spending another dime." \xe2\x80\x94 by @yanhuangwrites https://t.co/N2pOmi5Kw5']
ALL DATA: {b'lang': b'en', b'favorite_count': b'0', b'text': b'"7 hard truths you need to know before spending another dime." \xe2\x80\x94 by @yanhuangwrites https://t.co/N2pOmi5Kw5', b'source': b'<a href="https://buffer.com" rel="nofollow">Buffer</a>', b'retweet_count': b'0'}
========================================================================

Displaying Tweet with ID: b'1447764542532898824'
Text: [b'The Delhi govt began spraying the Pusa bio-decomposer across fields in the city to prevent stubble burning, Environ\xe2\x80\xa6 https://t.co/wPxXUL4hzm']
ALL DATA: {b'lang': b'en', b'favorite_count': b'4', b'text': b'The Delhi govt began spraying the Pusa bio-decomposer across fields in the city to prevent stubble burning, Environ\xe2\x80\xa6 https://t.co/wPxXUL4hzm', b'source': b'<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>', b'retweet_count': b'3'}
========================================================================

Displaying Tweet with ID: b'1447764210876776450'
Text: [b'The UP government has issued guidelines for celebrating Navratri, Dussehra and Chehallum while asking for strict ad\xe2\x80\xa6 https://t.co/IMQGWZKoj0']
ALL DATA: {b'lang': b'en', b'favorite_count': b'11', b'text': b'The UP government has issued guidelines for celebrating Navratri, Dussehra and Chehallum while asking for strict ad\xe2\x80\xa6 https://t.co/IMQGWZKoj0', b'source': b'<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>', b'retweet_count': b'3'}
========================================================================

Displaying Tweet with ID: b'1447763994475859968'
Text: [b'RT @Showbiz_IT: #AishwaryaRai wishes #AmitabhBachchan on birthday, shares his pic with #AaradhyaBachchan\n\nhttps://t.co/M0rKzCwsoL']
ALL DATA: {b'lang': b'en', b'favorite_count': b'0', b'text': b'RT @Showbiz_IT: #AishwaryaRai wishes #AmitabhBachchan on birthday, shares his pic with #AaradhyaBachchan\n\nhttps://t.co/M0rKzCwsoL', b'source': b'<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>', b'retweet_count': b'2'}
========================================================================

<div style="font-size:30px;color:#3665af;background-color:#E9E9F5;padding:10px;">
    4. Load Database From CSV
</div>

Unzip "CITES Wildlife Trade Database.zip" to get "comptab_2018-01-29 16_00_comma_separated.csv"
### Question 11:
Load this csv file into REDIS and compute the number of animals per Order for each importer. Your output should be similar to this:
<br>

US . Carnivora . XXX
<br>
US . Falconiformes . XXX
<br>
US . Artiodactyla . XXX
<br>
...
<br>
AD . Acipenseriformes . XXX
<br>
AD . Falconiformes . XXX
<br>
AD . Carnivora . XXX
<br>
...

Measure the running time, and present the average running time for the load and the processing operations.

**Please also explain your code**
<br>
Hint: You can download CITES Wildlife Trade Database.zip, unzip it and open comptab_2018-01-29 16_00_comma_separated.csv to see the data

<span style="color:RED">PLACE YOUR ANSWERS/CODE IN CELLS BELOW</span>

In [24]:
import zipfile
import numpy as np
import pandas as pd


with zipfile.ZipFile("CITES Wildlife Trade Database.zip","r") as zip_ref:
    zip_ref.extractall("")

In [30]:
animal_df = pd.read_csv("comptab_2018-01-29 16_00_comma_separated.csv", sep=",")
order_count = animal_df.groupby(['Importer','Order'])['Importer reported quantity'].sum().reset_index()

In [31]:
for i in order_count.iterrows():
    result_set = {
        "Importer" : i[1]["Importer"],
        "Order" : i[1]["Order"],
        "Quantity": i[1]["Importer reported quantity"]
    }
    
    myRedis.hmset(i[0], result_set)
    
    myRedis.rpush("animalQuantity",str(i[0]))

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:8: DeprecationWarning: Redis.hmset() is deprecated. Use Redis.hset() instead.

In [32]:
for id in myRedis.lrange("animalQuantity",0,99):
    print()
    print("Displaying animal Quantity with ID:",id)
    print("Quantity:",myRedis.hmget(id,"Quantity"))
    print("ALL DATA:",myRedis.hgetall(id))
    print("========================================================================")

Displaying animal Quantity with ID: b'0'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AD', b'Order': b'Acipenseriformes', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'1'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AD', b'Order': b'Anseriformes', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'2'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AD', b'Order': b'Artiodactyla', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'3'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AD', b'Order': b'Carnivora', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'4'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AD', b'Order': b'Crocodylia', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'5'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AD', b'Order': b'Gorgonacea', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'6'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AD', b'Order': b'Proboscidea', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'7'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AD', b'Order': b'Sauria', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'8'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AD', b'Order': b'Serpentes', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'9'
Quantity: [b'1402355.8280000002']
ALL DATA: {b'Importer': b'AE', b'Order': b'Acipenseriformes', b'Quantity': b'1402355.8280000002'}
========================================================================

Displaying animal Quantity with ID: b'10'
Quantity: [b'8.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Anseriformes', b'Quantity': b'8.0'}
========================================================================

Displaying animal Quantity with ID: b'11'
Quantity: [b'12.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Anura', b'Quantity': b'12.0'}
========================================================================

Displaying animal Quantity with ID: b'12'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Apiales', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'13'
Quantity: [b'21.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Artiodactyla', b'Quantity': b'21.0'}
========================================================================

Displaying animal Quantity with ID: b'14'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Asterales', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'15'
Quantity: [b'133.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Carnivora', b'Quantity': b'133.0'}
========================================================================

Displaying animal Quantity with ID: b'16'
Quantity: [b'12674.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Caryophyllales', b'Quantity': b'12674.0'}
========================================================================

Displaying animal Quantity with ID: b'17'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Ceratodontiformes', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'18'
Quantity: [b'16.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Ciconiiformes', b'Quantity': b'16.0'}
========================================================================

Displaying animal Quantity with ID: b'19'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Columbiformes', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'20'
Quantity: [b'1004.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Crocodylia', b'Quantity': b'1004.0'}
========================================================================

Displaying animal Quantity with ID: b'21'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Cuculiformes', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'22'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Cyatheales', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'23'
Quantity: [b'30.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Cycadales', b'Quantity': b'30.0'}
========================================================================

Displaying animal Quantity with ID: b'24'
Quantity: [b'77969.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Euphorbiales', b'Quantity': b'77969.0'}
========================================================================

Displaying animal Quantity with ID: b'25'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Fabales', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'26'
Quantity: [b'6330.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Falconiformes', b'Quantity': b'6330.0'}
========================================================================

Displaying animal Quantity with ID: b'27'
Quantity: [b'11.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Galliformes', b'Quantity': b'11.0'}
========================================================================

Displaying animal Quantity with ID: b'28'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Gentianales', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'29'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Gorgonacea', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'30'
Quantity: [b'403.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Gruiformes', b'Quantity': b'403.0'}
========================================================================

Displaying animal Quantity with ID: b'31'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Helioporacea', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'32'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Lepidoptera', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'33'
Quantity: [b'408.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Liliales', b'Quantity': b'408.0'}
========================================================================

Displaying animal Quantity with ID: b'34'
Quantity: [b'2260.7']
ALL DATA: {b'Importer': b'AE', b'Order': b'Mesogastropoda', b'Quantity': b'2260.7'}
========================================================================

Displaying animal Quantity with ID: b'35'
Quantity: [b'13.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Milleporina', b'Quantity': b'13.0'}
========================================================================

Displaying animal Quantity with ID: b'36'
Quantity: [b'4961234.937000001']
ALL DATA: {b'Importer': b'AE', b'Order': b'Myrtales', b'Quantity': b'4961234.937000001'}
========================================================================

Displaying animal Quantity with ID: b'37'
Quantity: [b'360.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Nepenthales', b'Quantity': b'360.0'}
========================================================================

Displaying animal Quantity with ID: b'38'
Quantity: [b'231565.0']

ALL DATA: {b'Importer': b'AE', b'Order': b'Orchidales', b'Quantity': b'231565.0'}
========================================================================

Displaying animal Quantity with ID: b'39'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Osteoglossiformes', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'40'
Quantity: [b'50.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Passeriformes', b'Quantity': b'50.0'}
========================================================================

Displaying animal Quantity with ID: b'41'
Quantity: [b'2.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Perissodactyla', b'Quantity': b'2.0'}
========================================================================

Displaying animal Quantity with ID: b'42'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Pinales', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'43'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Primates', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'44'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Proboscidea', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'45'
Quantity: [b'2732.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Psittaciformes', b'Quantity': b'2732.0'}
========================================================================

Displaying animal Quantity with ID: b'46'
Quantity: [b'12.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Rheiformes', b'Quantity': b'12.0'}
========================================================================

Displaying animal Quantity with ID: b'47'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Sapindales', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'48'
Quantity: [b'268.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Sauria', b'Quantity': b'268.0'}
========================================================================

Displaying animal Quantity with ID: b'49'
Quantity: [b'2204.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Scleractinia', b'Quantity': b'2204.0'}
========================================================================

Displaying animal Quantity with ID: b'50'
Quantity: [b'7600.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Serpentes', b'Quantity': b'7600.0'}
========================================================================

Displaying animal Quantity with ID: b'51'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Stolonifera', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'52'
Quantity: [b'2.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Strigiformes', b'Quantity': b'2.0'}
========================================================================

Displaying animal Quantity with ID: b'53'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Stylasterina', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'54'
Quantity: [b'149.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Testudines', b'Quantity': b'149.0'}
========================================================================

Displaying animal Quantity with ID: b'55'
Quantity: [b'21.0']
ALL DATA: {b'Importer': b'AE', b'Order': b'Veneroida', b'Quantity': b'21.0'}
========================================================================

Displaying animal Quantity with ID: b'56'
Quantity: [b'3200.0']
ALL DATA: {b'Importer': b'AF', b'Order': b'Bromeliales', b'Quantity': b'3200.0'}
========================================================================

Displaying animal Quantity with ID: b'57'
Quantity: [b'1500.0']
ALL DATA: {b'Importer': b'AF', b'Order': b'Cycadales', b'Quantity': b'1500.0'}
========================================================================

Displaying animal Quantity with ID: b'58'
Quantity: [b'159800.0']
ALL DATA: {b'Importer': b'AF', b'Order': b'Liliales', b'Quantity': b'159800.0'}
========================================================================

Displaying animal Quantity with ID: b'59'
Quantity: [b'3185.0']
ALL DATA: {b'Importer': b'AF', b'Order': b'Orchidales', b'Quantity': b'3185.0'}
========================================================================

Displaying animal Quantity with ID: b'60'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AF', b'Order': b'Psittaciformes', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'61'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AG', b'Order': b'Acipenseriformes', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'62'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AG', b'Order': b'Crocodylia', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'63'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AG', b'Order': b'Cycadales', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'64'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AG', b'Order': b'Liliales', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'65'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AG', b'Order': b'Orchidales', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'66'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AG', b'Order': b'Sapindales', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'67'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AI', b'Order': b'Cycadales', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'68'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AL', b'Order': b'Acipenseriformes', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'69'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AL', b'Order': b'Artiodactyla', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'70'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AL', b'Order': b'Carnivora', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'71'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AL', b'Order': b'Caryophyllales', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'72'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AL', b'Order': b'Crocodylia', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'73'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AL', b'Order': b'Euphorbiales', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'74'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AL', b'Order': b'Liliales', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'75'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AL', b'Order': b'Orchidales', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'76'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AL', b'Order': b'Psittaciformes', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'77'
Quantity: [b'0.0']

ALL DATA: {b'Importer': b'AL', b'Order': b'Sauria', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'78'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AL', b'Order': b'Serpentes', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'79'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AM', b'Order': b'Acipenseriformes', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'80'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AM', b'Order': b'Artiodactyla', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'81'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AM', b'Order': b'Carnivora', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'82'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AM', b'Order': b'Caryophyllales', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'83'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AM', b'Order': b'Crocodylia', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'84'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AM', b'Order': b'Cycadales', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'85'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AM', b'Order': b'Falconiformes', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'86'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AM', b'Order': b'Liliales', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'87'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AM', b'Order': b'Milleporina', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'88'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AM', b'Order': b'Nepenthales', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'89'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AM', b'Order': b'Orchidales', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'90'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AM', b'Order': b'Proboscidea', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'91'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AM', b'Order': b'Psittaciformes', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'92'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AM', b'Order': b'Sauria', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'93'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AM', b'Order': b'Scleractinia', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'94'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AM', b'Order': b'Serpentes', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'95'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AN', b'Order': b'Acipenseriformes', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'96'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AN', b'Order': b'Crocodylia', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'97'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AN', b'Order': b'Psittaciformes', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'98'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AN', b'Order': b'Sauria', b'Quantity': b'0.0'}
========================================================================

Displaying animal Quantity with ID: b'99'
Quantity: [b'0.0']
ALL DATA: {b'Importer': b'AN', b'Order': b'Testudines', b'Quantity': b'0.0'}
========================================================================

<div style="font-size:20px;background-color:#BE6D00;color:#F6EFE5;padding:10px;text-align:center;">
STOP YOUR CLUSTER WHEN YOU ARE NOT WORKING<br><br>
ONCE YOU ARE FINISHED, DELETE YOUR CLUSTER
</div>
<br>

<hr style="border-top: 5px solid purple; margin-top: 1px; margin-bottom: 1px"></hr>

<hr style="border-top: 5px solid orange; margin-top: 1px; margin-bottom: 1px"></hr>

Submission: Once you're finished, select "Save and Checkpoint" in the File menu and then execute the submit cell below. The result will contain a link that you can use to check that your assignment has been submitted successfully. If you submit more than once before the deadline, we will only grade your final submission. If you mistakenly submit the wrong one, you can go to the URL that you got at the very beginning of this homework and flag the correct version. To do so, go to the website, click on this assignment, and find the version you would like to have graded. There should be an option to flag that submission for grading. Good luck!

In [34]:
_ = ok.submit()

Saving notebook... Saved 'Assignment2.ipynb'.
Performing authentication
Please enter your bCourses email: vijayasimha.bheemireddy@ucdenver.edu
Unable to find an open port for authentication.

Copy the following URL and open it in a web browser. To copy,
highlight the URL, right-click, and select "Copy".

https://kubemaster.ucdenver.pvt:5000/client/login/

After logging in, copy the code from the web page, paste it below,
and press Enter. To paste, right-click and select "Paste".

Paste your code here: R8cID3EzFmyL9UUXhtJT16VxlwACGs

/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,

Successfully logged in as vijayasimha.bheemireddy@ucdenver.edu
Submit... 100% complete
Submission successful for user: vijayasimha.bheemireddy@ucdenver.edu
URL: https://kubemaster.ucdenver.pvt:5000/UCDenver/CSCI4951-5951/fa21/assignment2/submissions/dRglEe

<hr style="border-top: 5px solid orange; margin-top: 1px; margin-bottom: 1px"></hr>